insert into GAMESUMMARY (CLIENTGESTURE, SERVERGESTURE, RESULT, TIMEPLAYED)
values('ROCK','ROCK','TIE','2010-05-12 00:00:00.0');
insert into GAMESUMMARY (CLIENTGESTURE, SERVERGESTURE, RESULT, TIMEPLAYED)
values('PAPER','ROCK','WIN','2011-05-12 00:00:00.0');
insert into GAMESUMMARY (CLIENTGESTURE, SERVERGESTURE, RESULT, TIMEPLAYED)
values('SCISSORS','ROCK','LOSS','2012-05-12 00:00:00.0');
insert into EVENTS (CODE, TITLE, DESCRIPTION)
values('FMSC170', 'Family Science', 'Learn about xyz');
insert into EVENTS (CODE, TITLE, DESCRIPTION)
values('CMSC399', 'Intro to Music', 'introduction to music');
insert into CUSTOMERS (USERID, NAME, EMAIL, TIMESTARTED)
values(123,'Jay-Z', 'jayz@gmail.com','2012-05-12 00:00:00.0');
insert into REGISTRATIONS (REGISTRATIONID, EVENTID, REGISTRATIONDATE, NOTES)
values ('10', '1', '2024-07-28 00:00:00.0', 'this is a test event3');
