insert into GAMESUMMARY (CLIENTGESTURE, SERVERGESTURE, RESULT, TIMEPLAYED)
values('ROCK','ROCK','TIE','2010-05-12 00:00:00.0');
insert into GAMESUMMARY (CLIENTGESTURE, SERVERGESTURE, RESULT, TIMEPLAYED)
values('PAPER','ROCK','WIN','2011-05-12 00:00:00.0');
insert into GAMESUMMARY (CLIENTGESTURE, SERVERGESTURE, RESULT, TIMEPLAYED)
values('SCISSORS','ROCK','LOSS','2012-05-12 00:00:00.0');
insert into EVENTS (EVENTID, CODE, TITLE, DESCRIPTION)
values(1, 'FMSC170', 'Family Science', 'Learn about xyz');
insert into EVENTS (EVENTID, CODE, TITLE, DESCRIPTION)
values(2, 'CMSC399', 'Intro to Music', 'introduction to music');
insert into CUSTOMERS (CUSTOMERID, NAME, EMAIL, PASSWORD)
values(1, 'Jay-Z', 'jayz@gmail.com','2abcd123');

